module.exports = {
  SUCCESSFULLY: "Successfully",
  SOMETHING_WENT_WRONG: "Something went wrong",
  UNAUTHORIZED: "Unauthorized",
  RUNDOWN_ERROR: "Rundown API error",
  USER_NOT_EXISTS: "User doesn't exists",
  INVALID_CREDS: "Invalid Credentials",
  REGISTER_SUCCESSFULLY: "Register Successfully",
  LOGIN_SUCCESSFULLY: "Login Successfully",
  LOGOUT_SUCCESSFULLY: "Logout Successfully",
  LOGOUT_SUCCESSFULLY_ALL_USERS: "All Users Successfully Logout",
  BLOCKED: "User is blocked",
  FORBIDDEN: "Access Denied",
  VALIDATION: "Validation Error",
  CREATED_SUCCESSFULLY: "Created Successfully",
  UPDATED_SUCCESSFULLY: "Updated Successfully",
  FETCHED_SUCCESSFULLY: null,
  DELETED_SUCCESSFULLY: "Deleted Successfully",
  ALREADY_EXISTS: "Already exists",
  INACTIVE_ACCOUNT: "Inactive account",
  EMAIL_ALREADY_EXISTS: "Email already exists",
  USERNAME_ALREADY_EXISTS: "User ID already exists",
  OUT_ATTENDANCE_EXISTS:
    "You cannot login for today as you have already logout",
  UPLOADED_SUCESSFULLY: null,
  INVALID_ATTENDANCE_SLOT: "Attendance Slot does not exist",
  ATTENDANCE_MARKED: "Attendance marked Successfully",
  ATTENDANCE_ALREADY_MARKED: "Attendance already marked",
  ATTENDANCE_COMPLETE: "Your today's attendance is complete",
  ATTENDANCE_MISSED: "You missed your attendance",
  NO_REMAINING_SLOTS: "No remaining slots available",
  VERIFICATION_PENDING:
    "Your request for verification is pending administrative approval.",
  VERIFICATION_REJECTED:
    "Your verification request has been rejected by the administrator.",
  INVALID_PINCODE: "Invalid pincode",
  INVALID_API_KEY: "Invalid API Key",
  INVALID_RESET_TOKEN: "Invalid Reset Password Token",
  NOTIFICATION_SEND_SUCCESSFULLY: "Notification send Successfully",
  EMAIL_SEND_SUCCESSFULLY: "Email send Successfully",
  PASSWORD_CHANGED_SUCCESSFULLY: "Password Changed Successfully",
  TRANSFER_ACCOUNT: "Your Account is Transfered",
  TRANSFER_ACCOUNT_SUCCESSFULLY: "Transfer Account Sucessfully",
  NULL: null,
};
